version: "3.7"

services:
  app:
    container_name: susunjadwal
    build: .
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    command: flask run
    volumes:
      - .:/code
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mongo
    container_name: ristek-mongo
    ports:
      - 37017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
      - MONGO_INITDB_DATABASE=test
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
